name: build

on:
  pull_request:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t lyzhang1999/frontend:${{ github.sha }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push the Docker image
        run: docker push lyzhang1999/frontend:${{ github.sha }}
